[build]
builder = "DOCKERFILE"
dockerfilePath = "Jica/Dockerfile"

[deploy]
startCommand = "dotnet Jica.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 